name: Integration tests
on: [workflow_dispatch]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Update the system
        run: |
          sudo apt update -y
      - name: Install dependencies
        run: |
          sudo apt install -y git=2.34.1 shunit2 bsdmainutils \
          python3-docutils pulseaudio-utils dunst sphinx-doc \
          graphviz dvipng latexmk librsvg2-bin texlive-xetex \
          python3-sphinx python3-dask-sphinx-theme lzip \
          lzop git-email pv ccache libemail-valid-perl libmailtools-perl \
          libauthen-sasl-perl libio-socket-ssl-perl
      - name: Prepare for tests
        run: |
          ./setup.sh --install <<< 'y'
          source $HOME/.bashrc
          git config --global user.email "kw@kworkflow.net"
          git config --global user.name "Kworkflow"
      - name: Integration tests
        run: |
          ./run_integration_tests.sh
