name: Integration tests
on: [workflow_dispatch]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Update the system
        run: |
          sudo apt update -y
      - name: Install dependencies
        run: |
          sudo apt install -y shunit2 bc sqlite3 bsdmainutils
      - name: Prepare for tests
        run: |
          ./setup.sh --install <<< 'y'
          source $HOME/.bashrc
          git config --global user.email "kw@kworkflow.net"
          git config --global user.name "Kworkflow"
      - name: Integration tests
        run: |
          ./run_integration_tests.sh
